#!/bin/bash

PATH=${PATH}:${POSTGRESQL_BIN_DIR}

# Define mandatory variable
POSTGRESQL_LISTEN_ADDRESS=${POSTGRESQL_LISTEN_ADDRESS:-"0.0.0.0"}
POSTGRESQL_LISTEN_PORT=${POSTGRESQL_LISTEN_PORT:-"5432"}

POSTGRESQL_OPTS="-h ${POSTGRESQL_LISTEN_ADDRESS} -p ${POSTGRESQL_LISTEN_PORT} -D ${POSTGRESQL_DATA_DIR}"

if [[ $1 = 'postgres' ]]
  then exec $@ ${POSTGRESQL_OPTS}
  else exec $@
fi
