---

#
#
#

revisionHistoryLimit: 3
replicaCount: 1
image:
  name: python-api
  tag: "1.0"
  pullPolicy: Never
service:
  type: ClusterIP
  port: 5000
env:
  APP_ADDRESS: "0.0.0.0"
  APP_PORT: 5000
  POSTGRESQL_DATABASE_NAME: "passengers"
  POSTGRESQL_DATABASE_USER: "titanic"
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/redirect-entry-point: https
    ingress.kubernetes.io/redirect-permanent: "true"
  path: /
  hosts:
    - localhost
affinity:
  matchExpressionKey: kubernetes.io/python-api
