---

#
#
#

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    tier: database
spec:
  type: "{{ .Values.service.type }}"
  ports:
  - name: postgresql
    port: {{ .Values.service.port }}
    targetPort: postgresql
  selector:
    app: "{{ .Chart.Name }}"
